variables:
  CONAN_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  CONAN_PROJECT_NAME: $CI_PROJECT_NAME

stages:
  - build

before_script:
  - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/conan/conan.git

macos-mojave:
  stage: build
  variables:
    CONAN_APPLE_CLANG_VERSIONS: "10.0"
    CONAN_USER_HOME: $CI_PROJECT_DIR
  script:
    - python3 conan/gitlab-ci/build.py
  tags:
    - mojave