find_path(USB_INCLUDE_DIR NAMES libusb.h PATHS ${CONAN_INCLUDE_DIRS_LIBUSB}/libusb-1.0)
find_library(USB_LIBRARY NAMES ${CONAN_LIBS_LIBUSB} PATHS ${CONAN_LIB_DIRS_LIBUSB})

set(USB_FOUND TRUE)
set(USB_INCLUDE_DIRS ${USB_INCLUDE_DIR})
set(USB_LIBRARIES ${USB_LIBRARY})
mark_as_advanced(USB_LIBRARY USB_INCLUDE_DIR)