find_path(LIBUSB_INCLUDE_DIR NAMES /libusb-1.0/libusb.h PATHS ${CONAN_INCLUDE_DIRS_LIBUSB})
find_library(LIBUSB_LIBRARY NAMES usb-1.0 PATHS ${CONAN_LIB_DIRS_LIBUSB})

set(LIBUSB_FOUND TRUE)
set(LIBUSB_INCLUDE_DIRS ${LIBUSB_INCLUDE_DIR})
set(LIBUSB_LIBRARIES ${LIBUSB_LIBRARY})
mark_as_advanced(LIBUSB_LIBRARY LIBUSB_INCLUDE_DIR)