find_path(USB_INCLUDE_DIR NAMES libusb.h PATHS ${CONAN_INCLUDE_DIRS_USB})
find_library(USB_LIBRARY NAMES ${CONAN_LIBS_USB} PATHS ${CONAN_LIB_DIRS_USB})

set(USB_FOUND TRUE)
set(USB_INCLUDE_DIRS ${USB_INCLUDE_DIR})
set(USB_LIBRARIES ${USB_LIBRARY})
mark_as_advanced(USB_LIBRARY USB_INCLUDE_DIR)